# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\pytushar\openCv_Project\Attendance_system\windowMain\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(769, 516)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName("mdiArea")
        self.horizontalLayout.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuCreate = QtWidgets.QMenu(self.menubar)
        self.menuCreate.setObjectName("menuCreate")
        self.menuList = QtWidgets.QMenu(self.menubar)
        self.menuList.setObjectName("menuList")
        self.menuReport = QtWidgets.QMenu(self.menubar)
        self.menuReport.setObjectName("menuReport")
        MainWindow.setMenuBar(self.menubar)
        self.actionCreate_Teacher = QtWidgets.QAction(MainWindow)
        self.actionCreate_Teacher.setObjectName("actionCreate_Teacher")
        self.actionCreate_Student = QtWidgets.QAction(MainWindow)
        self.actionCreate_Student.setObjectName("actionCreate_Student")
        self.actionList_of_Student = QtWidgets.QAction(MainWindow)
        self.actionList_of_Student.setObjectName("actionList_of_Student")
        self.actionList_of_Teacher = QtWidgets.QAction(MainWindow)
        self.actionList_of_Teacher.setObjectName("actionList_of_Teacher")
        self.menuCreate.addAction(self.actionCreate_Teacher)
        self.menuCreate.addAction(self.actionCreate_Student)
        self.menuList.addAction(self.actionList_of_Student)
        self.menuList.addAction(self.actionList_of_Teacher)
        self.menubar.addAction(self.menuCreate.menuAction())
        self.menubar.addAction(self.menuList.menuAction())
        self.menubar.addAction(self.menuReport.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Attendence"))
        self.menuCreate.setTitle(_translate("MainWindow", "Create"))
        self.menuList.setTitle(_translate("MainWindow", "List"))
        self.menuReport.setTitle(_translate("MainWindow", "Report"))
        self.actionCreate_Teacher.setText(_translate("MainWindow", "Create Teacher"))
        self.actionCreate_Student.setText(_translate("MainWindow", "Create Student"))
        self.actionList_of_Student.setText(_translate("MainWindow", "List of student"))
        self.actionList_of_Teacher.setText(_translate("MainWindow", "List of Teacher"))
